name: test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  prod-test:
    name: Production Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Test with coverage
        run: go test -v ./... -coverprofile=coverage.out -covermode=count
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          file: coverage.out
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          
          
